rootProject.name = "Hyperion"

include("pluginmanager")
include("aggregator")
include("hyperionplugin")
include("hyperionplugin:common")
include("hyperionplugin:plugins:sampleplugin")
include("plugin")
include("pluginmanager")
include("pipeline")
include("pipeline:common")
include("pipeline:plugins:sample")
include("pipeline:plugins:renamer")
include("pipeline:plugins:pathextractor")
include("pipeline:plugins:extractor")
include("datasource")
include("datasource:common")
include("datasource:plugins:elasticsearch")
