name: "Plugin1"
redis:
  host: "192.168.2.168"
  port: 6379

field : "message"
match : "\\[.+?\\] INFO [^:]+:(\\d+) (-) .+"
extract :
  - to : "location.line"
    type : "number"
  - to : "dash"
    type : "string"