# Sets up redis, plugin manager and 3 sample plugins
# run this from top level

version: '3'
services:
  redis:
    image: "redis:latest"
  pluginmanager:
    build:
      dockerfile: ../../../../../../../pluginmanager
      args:
        - configpath=pluginmanager.yaml
    ports:
      - "6379:6379"
  datasource:
    build:
      dockerfile: ../../../../../../../sampleplugin
      args:
        - configpath=datasource.yml
    ports:
      - "6379:6379"
  renamer:
    build:
      dockerfile: ../../../../../../../sampleplugin
      args:
        - configpath=renamer.yml
    ports:
      - "6379:6379"
  aggregator:
    build:
      dockerfile: ../../../../../../../sampleplugin
      args:
        - configpath=aggregator.yml
    ports:
      - "6379:6379"






