# Sets up redis, plugin manager and 3 sample plugins
# run this from top level

version: '3'
services:
  redis:
    image: "redis:latest"
  pluginmanager:
    build:
      dockerfile: ../../../../../../../pluginmanager
      args:
        - configpath=kip.yaml

    ports:
      - "6379:6379"
  # TODO: load sampleplugin three time, datasource, plugin, Aggregator





