version: '3.3'
services:
  gradle:
    build:
      context: ../
      dockerfile: src/Dockerfile
    environment:
      - GRADLE_HOME_DIR=/home/gradle/cache
    volumes:
      - gradle_cache:/home/gradle/cache
      - ${HYPERION_ROOT_DIR}/:/home/gradle/project

volumes:
  gradle_cache: