# Sets up postgres and the plugin manager.
# The Elasticsearch datasource is used in combination with the renamer to feed the aggregator.

version: '3.3'
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - hyperion
    ports:
      - "5432:5432"

  pluginmanager:
    build:
      context: ${HYPERION_ROOT_DIR}/pluginmanager
    volumes:
      - type: bind
        source: ./pluginmanager.yml
        target: /usr/config.yml
    environment:
      - CONFIGPATH=/usr/config.yml
    networks:
      - hyperion

  datasource:
    build:
      context: ${HYPERION_ROOT_DIR}/datasource/plugins/elasticsearch
    volumes:
      - type: bind
        source: ./datasource.yml
        target: /usr/config.yml
    environment:
      - CONFIGPATH=/usr/config.yml
    networks:
      - hyperion
    depends_on:
      - pluginmanager

  renamer:
    build:
      context: ${HYPERION_ROOT_DIR}/pipeline/plugins/renamer
    volumes:
      - type: bind
        source: ./renamer.yml
        target: /usr/config.yml
    environment:
      - CONFIGPATH=/usr/config.yml
    networks:
      - hyperion
    depends_on:
      - pluginmanager

  aggregator:
    build:
      context: ${HYPERION_ROOT_DIR}/aggregator
    volumes:
      - type: bind
        source: ./aggregator.yml
        target: /usr/config.yml
    environment:
      - HYPERION_AGGREGATOR_CONFIG=/usr/config.yml
    networks:
      - hyperion
    depends_on:
      - pluginmanager
      - postgres
    ports:
      - "8081:8081"

networks:
  hyperion:
