# Runs Gradle Check on the aggregator module
# Will be triggered on every pull request and push to master
# Only commences on check if the code changed
name: Gradle check Aggregator

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  gradle-check:
    runs-on: ubuntu-latest

    services:
      dind:
        image: docker

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: marceloprado/has-changed-path@master
        id: hyperion-aggregator
        with:
          paths: aggregator/

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradle check aggregator
        if: steps.hyperion-aggregator.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        env:
          DOCKER_HOST: "tcp://dind:2375"
          DOCKER_DRIVER: overlay2
        with:
          arguments: :aggregator:check