# Runs Gradle Check on the datasource common module and plugins
# Will be triggered on every pull request and push to master
# Only commences on check if the code changed
name: Gradle check elasticsearch plugin

on:
  pull_request:
    paths:
      - 'datasource/plugins/elasticsearch/**'
  push:
    branches:
      - master

jobs:
  gradle-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-datasource_elasticsearch-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-datasource_elasticsearch-gradle-

      - name: gradle check elasticsearch plugin
        if: steps.hyperion-datasource-elasticsearch.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :datasource:plugins:elasticsearch:check
