# When a commit is pushed to master with a tag matching v*, create a new release.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-aggregator-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-aggregator-gradle-

      - name: gradle docker-release
        uses: eskatos/gradle-command-action@v1
        env:
          D_USR: $ {{ secrets.DOCKER_USERNAME }}
          D_PWD: $ {{ secrets.DOCKER_PASSWORD }}
          D_EMAIL: $ {{ secrets.DOCKER_EMAIL }}
        with:
          arguments: docker-release -PdockerUsername="$D_USR" -PdockerPassword="$D_PWD" -PdockerEmail="$D_EMAIL"
