# Runs Gradle Check on every pull request and push to master
# Only runs Gradle Check on changed modules
name: Gradle check Hyperion

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: marceloprado/has-changed-path@master
        id: hyperion-aggregator
        with:
          paths: aggregator/

      - uses: marceloprado/has-changed-path@master
        id: hyperion-plugin
        with:
          paths: plugin/

      - uses: marceloprado/has-changed-path@master
        id: hyperion-pipeline-common
        with:
          paths: pipeline/common

      - uses: marceloprado/has-changed-path@master
        id: hyperion-pipeline-extractor
        with:
          paths: pipeline/plugins/extractor

      - uses: marceloprado/has-changed-path@master
        id: hyperion-pipeline-pathextractor
        with:
          paths: pipeline/plugins/pathextractor

      - uses: marceloprado/has-changed-path@master
        id: hyperion-pipeline-renamer
        with:
          paths: pipeline/plugins/renamer

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradle check aggregator
        if: steps.hyperion-aggregator.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :aggregator:check

      - name: gradle check plugin
        if: steps.hyperion-plugin.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :plugin:check

      - name: gradle check pipeline common
        if: steps.hyperion-pipeline.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :pipeline:common:check

      - name: gradle check pipeline renamer plugin
        if: steps.hyperion-pipeline-renamer.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :pipeline:plugins:renamer:check

      - name: gradle check pipeline extractor plugin
        if: steps.hyperion-pipeline-extractor.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :pipeline:plugins:extractor:check

      - name: gradle check pipeline pathextractor plugin
        if: steps.hyperion-pipeline-pathextractor.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :pipeline:plugins:pathextractor:check
