# Runs Gradle Check on the pipeline common module and plugins
# Will be triggered on every pull request and push to master
# Only commences on check if the code changed
name: Gradle check Pipeline

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  gradle-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: marceloprado/has-changed-path@master
        id: hyperion-pipeline-versiontracker
        with:
          paths: pipeline/pipeline/versiontracker

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradle check pipeline versiontracker plugin
        if: steps.hyperion-pipeline-versiontracker.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :pipeline:plugins:versiontracker:check