# Runs Gradle Check on the pipeline pathextractor plugin
# Will be triggered on every pull request and push to master
# Only commences on check if the code changed
name: Gradle check pipeline pathextractor plugin

on:
  pull_request:
    paths:
      - 'pipeline/plugins/pathextractor/**'
  push:
    branches:
      - master

jobs:
  gradle-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-pipeline_pathextractor-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-pipeline_pathextractor-gradle

      - name: gradle check plugin
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :pipeline:plugins:pathextractor:check
