# Runs Gradle Check on the Plugin module
# Will be triggered on every pull request and push to master
# Only commences on check if the code changed
name: Gradle check Plugin

on:
  pull_request:
    paths:
      - 'plugin/**'
  push:
    branches:
      - master

jobs:
  gradle-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-plugin-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-plugin-gradle-

      - name: gradle check plugin
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :plugin:check
