# Runs Gradle Check on the PluginManager module
# Will be triggered on every pull request and push to master
# Only commences on check if the code changed
name: Gradle check PluginManager

on:
  pull_request:
    paths:
      - 'pluginmanager/**'
  push:
    branches:
      - master

jobs:
  gradle-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-pluginmanager-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-pluginmanager-gradle-

      - name: gradle check pluginmanager
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :pluginmanager:check
