# Runs Gradle Check on the Plugin module
# Will be triggered on every pull request and push to master
# Only commences on check if the code changed
name: Gradle check Plugin

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  gradle-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: marceloprado/has-changed-path@master
        id: hyperion-plugin
        with:
          paths: plugin/

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - uses: actions/cache@v1
        if: steps.hyperion-plugin.outputs.changed == 'true'
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradle check plugin
        if: steps.hyperion-plugin.outputs.changed == 'true'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :plugin:check